version: '3.2'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    container_name: phpmyadmin
    restart: always
    ports:
      - "8085:80"
    environment:
      PMA_HOST: mysql

networks:
  default:
    external:
      name: technical_share
