version: '3.2'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend
    env_file:
      - ./.env
    volumes:
      - './:/app'
    ports:
      - '3000:3000'
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - '6033:3306'
    volumes:
      - 'v_mysql:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'dev'
      MYSQL_PASSWORD: 'dev'
      MYSQL_DATABASE: 'squad_28_technical_share'

networks:
  default:
    external:
      name: squad_28_technical_share

volumes:
  v_mysql:
    external: true
