module.exports = {
  clearMocks: true,
  // resetMocks: false,
  // resetModules: false,
  // restoreMocks: false,
  // collectCoverageFrom: [
  //   'src/**/*.ts',
  //   '!src/server.ts',
  //   '!src/app.ts',
  //   '!src/config',
  //   '!src/routes',
  //   '!src/database',
  // ],
  // coverageDirectory: 'coverage',
  // coveragePathIgnorePatterns: ['node_modules'],
  // transformIgnorePatterns: ['node_modules'],
  // watchPathIgnorePatterns: ['node_modules'],
  // modulePathIgnorePatterns: ['node_modules'],
  testPathIgnorePatterns: ['old-*', 'teste-*', 'dist', 'src'],
  // testMatch: ['.(spec|test).(js|ts)$'],
  // testRegex: ['test/**/*.(spec|test).(js|ts)'],
  transform: { '\\.(js|jsx|ts|tsx)$': '@sucrase/jest-plugin' },
  coverageProvider: 'v8',
  // coverageReporters: ['text', 'lcov'],
};
