name: Complete pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    types: [opened, reopened]
    branches: [main, master]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        mysql-version: [8.0]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Rename .env.example
        run: cp .env.example .env

      - name: Run all test
        run: yarn test

  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy application
        if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'squad-28-technical-share'
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
